# Generated by Django 3.1.7 on 2021-08-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregister',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
