# Generated by Django 3.1.7 on 2021-08-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210820_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
