# Generated by Django 3.2.3 on 2021-09-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_employee_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
