# Generated by Django 3.2.3 on 2021-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_employee_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
