# Generated by Django 3.1.7 on 2021-08-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('AddPosts', 'Review')
    ]
